# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_ps_cpp <- function(ks, alpha, delta) {
    .Call('_rre_log_ps_cpp', PACKAGE = 'rre', ks, alpha, delta)
}

marginal_negative_binomial_cpp <- function(k, alpha, delta) {
    .Call('_rre_marginal_negative_binomial_cpp', PACKAGE = 'rre', k, alpha, delta)
}

log_marginal_negative_binomial_cpp <- function(k, alpha, delta) {
    .Call('_rre_log_marginal_negative_binomial_cpp', PACKAGE = 'rre', k, alpha, delta)
}

loglike_cond_cpp <- function(alpha, delta, cc, ks, fs) {
    .Call('_rre_loglike_cond_cpp', PACKAGE = 'rre', alpha, delta, cc, ks, fs)
}

log_factorial_cpp <- function(x) {
    .Call('_rre_log_factorial_cpp', PACKAGE = 'rre', x)
}

loglike_unpenalized_cpp <- function(x, ccc, cc, ks, fs) {
    .Call('_rre_loglike_unpenalized_cpp', PACKAGE = 'rre', x, ccc, cc, ks, fs)
}

